### ISSUE TITLE
Simplifying amap usage

### ISSUE THREAD

**Issue by florimondmanca** [florimondmanca/aiometer#18]
Reading through the docs it came to my mind that the `async with` usage of `amap` doesn’t “look necessary” from a UX perspective.

When using it we always have to do *two things*:

- Enter a context with `async with` (*looks* like an implementation detail)
- Iterate over results with `async for`

As a user really only care about the second operation.

So what if we moved `async with` inside the implementation of amap, so that users can just do...

```python
results = [result async for result in amap(process, items)]
```

**Comment by graingert** [comment]
you can do this but you'd need to pass the TaskGroup into the amap, and wrap it with aclosing:


```python
async with anyio.create_task_group() as tg:
    async with aclosing(amap(process, items, tg)) as aiter:
        results = [result async for result in aiter]
```

**Comment by florimondmanca** [comment]
@graingert Well indeed, good point. The actual correct comparison would then be this…

_(Current situation)_
```python
async with aiometer.amap(process, items) as aiter:
    results = [result async for result in aiter]
```

Compared to this…

_(Correct implementation of proposed idea)_

```python
async with anyio.create_task_group() as tg:
    async with aclosing(aiometer.amap(process, items, tg)) as aiter:
        results = [result async for result in aiter]
```

Which instantaneously seems like we don't want `amap` to change, and the `async with` (which ensures structured concurrency constraints) + `async for` is just fine (users would have to add it not to shoot themselves in the foot; and it's likely that an implementation would _require_ the correct implementation anyway, which means there's not even a semi-viable "just `async for`" alternative).

I think we can close this then?

**Comment by graingert** [comment]
> I think we can *aclose* this then?
