### ISSUE TITLE
requests as list

### ISSUE THREAD

**Issue by lordcris** [florimondmanca/aiometer#23]
I'm using your library to try and drop catch some domain names, so I query the api with the same request several times per second.
Do I have to always generate a list of requests with the same element repeated thousands of times or there is a more efficient way to do it?
Thanks

**Comment by florimondmanca** [comment]
@lordcris Hello! Not sure what kind of efficiency you're asking about, but you could try creating a list of `httpx.Request` objects once and for all, and reusing those to make requests. Without more info or sample code it's hard to say more though.

I'll close this for now, but if you have follow up questions feel free to reach out to the chat. :) https://gitter.im/encode/community

**Comment by lordcris** [comment]
> you could try creating a list of httpx.Request objects once and for all

This is what I'm doing:
`requests = [httpx.Request("GET", url)] * cycles`

cycles is a pretty big number ~1mln.
My question is: Is this the most efficient way to do it? By creating a large list populated with the same element.
I tried using generators but they don't have a fixed length and it doesn't work.
