### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by nardi** [florimondmanca/aiometer#31]
Could you update or loosen the version specifications in the requirements of the package? Specifically the restriction for `typing-extensions~=3.10` is conflicting for me, as I need a newer version.

**Comment by florimondmanca** [comment]
@nardi Sure. It's also possible we want to drop any upper pin in `install_requires`. So, dropping the one on `anyio` as well as `typing-extensions`. Would you be up to submitting a PR?

**Comment by ninoseki** [comment]
@florimondmanca Hello, could you please check my PR (#36) regarding this issue?

**Comment by florimondmanca** [comment]
Sure, looking into it now

**Comment by florimondmanca** [comment]
@ninoseki Would you take a look at #38? I relaxed the version requirement on `typing-extensions` there (dropped it, basically), that should resolve the problem reported here.

**Comment by ninoseki** [comment]
LGTM!
